$(document).ready(function(){
  $("#dLabel").click(function(event){
    $("#notify").text("");
    $.ajax({
      url:"adminData.cfc?method=markAsReadNotification",
      success:function(responseText){
        console.log(responseText);
      }
    })
  })
})
